supervillains = [
	("Abattoir", None),
	("Able Crown", None),
	("Abra Kadabra", None),
	("Absorbing Man", None),
	("Acolytes", None),
	("Acrobat", None),
	("Advanced Idea Mechanics", None),
	("Agamemno", None),
	("Agent H of HYDRA", None),
	("Al-Tariq", None),
	("Alberto Falcone", None),
	("Alex Wilder", None),
	("Alkhema", None),
	("Allatou", None),
	("Amazing Grace", None),
	("Amazo", None),
	("Americop", None),
	("Amos Fortune", None),
	("Amygdala", None),
	("Anaconda", None),
	("Anarky", None),
	("Animora", None),
	("Annihilus", None),
	("Anomaly", None),
	("Answer", None),
	("Anthony Lupus", None),
	("Apocalypse", None),
	("Appa Ali Apsa", None),
	("Aqueduct", None),
	("Arcade", None),
	("Aries", None),
	("Arkon", None),
	("Armadillo", None),
	("Artemis Crock", None),
	("Artemiz", None),
	("Asbestos Man", None),
	("Assembly of Evil", None),
	("Atomic Skull", None),
	("Attuma", None),
	("Axis Amerika", None),
	("Ballox the Monstroid", None),
	("Bane", None),
	("Baron Blitzkrieg", None),
	("Baron Blood", None),
	("Baron Mordo", None),
	("Baron Zemo", None),
	("Barracuda", None),
	("Batroc the Leaper", None),
	("Battleaxe", None),
	("Batzarro", None),
	("Bernadeth", None),
	("Bizarro", None),
	("Black Adam", None),
	("Black Flash", None),
	("Black Hand", None),
	("Black Knight", None),
	("Black Manta", None),
	("Black Mask", None),
	("Black Spider", None),
	("Black Talon", None),
	("Black Widow", None),
	("Black Zero", None),
	("Blackfire", None),
	("Blackout", None),
	("Blackrock", None),
	("Blacksmith", None),
	("Blastaar", None),
	("Blaze", None),
	("Blockbuster", None),
	("Bloodsport", None),
	("Bloody Mary", None),
	("Blue Snowman", None),
	("Blue Streak", None),
	("Bolivar Trask", None),
	("Brainiac", None),
	("Brainwave", None),
	("Bronze Tiger", None),
	("Brutale", None),
	("Bug-Eyed Bandit", None),
	("Bullseye", None),
	("Byth", None),
	("Calculator", None),
	("Calendar Man", None),
	("Captain Boomerang", None),
	("Captain Cold", None),
	("Captain Nazi", None),
	("Captain Stingaree", None),
	("Carmine Falcone", None),
	("Carnage", None),
	("Catman", None),
	("Catwoman", None),
	("Cavalier", None),
	("Chameleon", None),
	("Cheetah", None),
	("Cheshire", None),
	("Chessure", None),
	("Chronos", None),
	("Chthon", None),
	("Cicada", None),
	("Circe", None),
	("Clayface", None),
	("Clock King", None),
	("Cluemaster", None),
	("Cobalt Blue", None),
	("Cobalt Man", None),
	("Cold War", None),
	("Commissioner Gillian B. Loeb", None),
	("Composite Superman", None),
	("Conduit", None),
	("Constrictor", None),
	("Copperhead", None),
	("Cornelius Stirk", None),
	("Count Nefaria", None),
	("Count Vertigo", None),
	("Crazy Quilt", None),
	("Crime Doctor", None),
	("Crimesmith", None),
	("Crimson Dynamo", None),
	("Crossbones", None),
	("Crossfire", None),
	("Cutthroat", None),
	("Cyborgirl", None),
	("Dansen Macabre", None),
	("Dark Angel", None),
	("Darkseid", None),
	("Darth Vader", None),
	("David Cain", None),
	("Deacon Blackfire", None),
	("Deadline", None),
	("Deadpool", None),
	("Deadshot", None),
	("Death Storm", None),
	("Deathbird", None),
	("Deathbolt", None),
	("Deathstroke", None),
	("Decay", None),
	("Deep Six", None),
	("Desaad", None),
	("Despero", None),
	("Destiny", None),
	("Destroyer", None),
	("Deuce", None),
	("Deuce, Charger", None),
	("Devastation", None),
	("Devilance", None),
	("Diablo", None),
	("Diamond Lil", None),
	("Doctor Achilles Milo", None),
	("Doctor Alchemy", None),
	("Doctor Bedlam", None),
	("Doctor Cyber", None),
	("Doctor Demonicus", None),
	("Doctor Destiny", None),
	("Doctor Doom", None),
	("Doctor Double X", None),
	("Doctor Moon", None),
	("Doctor Octopus", None),
	("Doctor Phosphorus", None),
	("Doctor Poison", None),
	("Doctor Polaris", None),
	("Doctor Sivana", None),
	("Doctor Spectrum", None),
	("Dominus", None),
	("Doomsday", None),
	("Dormammu", None),
	("Double Dare", None),
	("Double Down", None),
	("Dr. Death", None),
	("Dr. Evil", None),
	("Dr. Horrible", None),
	("Dr. Light", None),
	("Dragon Man", None),
	("Dragonfly", None),
	("Dragonrider", None),
	("Duela Dent", None),
	("Eclipso", None),
	("Eduardo", None),
	("Effron the Sorcerer", None),
	("Egghead", None),
	("Electro", None),
	("Electrocutioner", None),
	("Elektro", None),
	("Emerald Empress", None),
	("Emma Frost", None),
	("Enchantress", None),
	("Equus", None),
	("Ereshkigal", None),
	("Evil Ernie", None),
	("Eviless", None),
	("Evinlea", None),
	("Executioner", None),
	("Exemplars", None),
	("Fabian Cortez", None),
	("Facade", None),
	("Factor Three", None),
	("Fadeaway Man", None),
	("Famine", None),
	("Faora", None),
	("Fatality", None),
	("Fault Zone", None),
	("Fearsome Five", None),
	("Fel Andar", None),
	("Felix Faust", None),
	("Fem Paragon", None),
	("Female Furies", None),
	("Fer-de-Lance", None),
	("Film Freak", None),
	("Fin Fang Foom", None),
	("Firebug", None),
	("Firefly", None),
	("Fisherman", None),
	("Fixer", None),
	("Flag-Smasher", None),
	("Floronic Man", None),
	("Freedom Force", None),
	("Frightful Four", None),
	("Fuzzy Lumpkins", None),
	("Galactus", None),
	("Gambler", None),
	("Gargantua", None),
	("Gargantus", None),
	("Gargoyle", None),
	("Gearhead", None),
	("Gemini", None),
	("General", None),
	("General Zod", None),
	("Gentleman Ghost", None),
	("Ghaur", None),
	("Giganta", None),
	("Gilotina", None),
	("Girder", None),
	("Gizmo", None),
	("Gladiator", None),
	("Glorious Godfrey", None),
	("Glorith", None),
	("Goddess", None),
	("Godiva", None),
	("Gog", None),
	("Golden Glider", None),
	("Goldface", None),
	("Goldilocks", None),
	("Googam", None),
	("Goom", None),
	("Gorilla Grodd", None),
	("Gorilla-Man", None),
	("Grand Director", None),
	("Granny Goodness", None),
	("Graviton", None),
	("Grayven", None),
	("Great White", None),
	("Green Goblin", None),
	("Griffin", None),
	("Grim Reaper", None),
	("Grottu", None),
	("Growing Man", None),
	("H.I.V.E.", None),
	("HYDRA", None),
	("Hades", None),
	("Halflife", None),
	("Hangman", None),
	("Hank Henshaw", None),
	("Harlequin", None),
	("Harley Quinn", None),
	("Harpy", None),
	("Hate-Monger", None),
	("Hath-Set", None),
	("Hazard", None),
	("Headlok", None),
	("Heat Wave", None),
	("Hector Hammond", None),
	("Heggra", None),
	("Hela", None),
	("Hellgrammite", None),
	("High Evolutionary", None),
	("Hitman", None),
	("Hobgoblin", None),
	("Holiday", None),
	("Hugo Strange", None),
	("Hulk Robot", None),
	("Humpty Dumpty", None),
	("Hush", None),
	("Hyathis", None),
	("Hyena", None),
	("Hyperion", None),
	("Hypnota", None),
	("Ibac", None),
	("Ignition", None),
	("Immortus", None),
	("Impala", None),
	("Imperiex", None),
	("Impossible Man", None),
	("Indigo", None),
	("Inertia", None),
	("Infant Terrible", None),
	("Inferno", None),
	("Ingra", None),
	("Intergang", None),
	("Ion", None),
	("Iron Maiden", None),
	("Jack Frost", None),
	("Jack O'Lantern", None),
	("Jason Kreis", None),
	("Jason Todd", None),
	("Javelin", None),
	("Jax-Ur", None),
	("Jewelee", None),
	("Jigsaw", None),
	("Jinx", None),
	("Joker", None),
	("Juggernaut", None),
	("KGBeast", None),
	("Kalibak", None),
	("Kang the Conqueror", None),
	("Kanjar Ro", None),
	("Kanto", None),
	("Killer Croc", None),
	("Killer Frost", None),
	("Killer Moth", None),
	("King Ghidorah", None),
	("King Shark", None),
	("King Snake", None),
	("Kingpin", None),
	("Kira", None),
	("Kite Man", None),
	("Klaw", None),
	("Kleinstocks", None),
	("Knockout", None),
	("Korvac", None),
	("Kraven the Hunter", None),
	("Krona", None),
	("Kryptonite Man", None),
	("Kulan Gath", None),
	("Kurrgo", None),
	("Kyle Abbot", None),
	("Lady Clay", None),
	("Lady Death", None),
	("Lady Deathstrike", None),
	("Lady Dorma", None),
	("Lady Mastermind", None),
	("Lady Octopus", None),
	("Lady Shiva", None),
	("Lady Spellbinder", None),
	("Lady Vic", None),
	("Lagomorph", None),
	("Lashina", None),
	("Lava Men", None),
	("Law", None),
	("Lazara", None),
	("League of Assassins", None),
	("Leap-Frog", None),
	("Leather", None),
	("Legion of the Unliving", None),
	("Letha", None),
	("Lethal Legion", None),
	("Lex Luthor", None),
	("Lion-Mane", None),
	("Livewire", None),
	("Living Laser", None),
	("Lloigoroth", None),
	("Llyra", None),
	("Lock-Up", None),
	("Lodestone", None),
	("Loki", None),
	("Lorelei", None),
	("Lotso", None),
	("Lucifer", None),
	("Lynx", None),
	("MODOK", None),
	("Mace Blitzkrieg", None),
	("Mad Harriet", None),
	("Mad Hatter", None),
	("Mad Thinker", None),
	("Madvillain", None),
	("Madame Masque", None),
	("Madame Rouge", None),
	("Madelyne Pryor", None),
	("Maelstrom", None),
	("Magenta", None),
	("Magneta", None),
	("Magneto", None),
	("Magpie", None),
	("Magus", None),
	("Mai Shen", None),
	("Major Disaster", None),
	("Major Force", None),
	("Malebolgia", None),
	("Malice", None),
	("Malice Vundabar", None),
	("Mammon", None),
	("Mammoth", None),
	("Man Beast", None),
	("Man-Bat", None),
	("Man-Killer", None),
	("Manchester Black", None),
	("Mandarin", None),
	("Mandarin's Minions", None),
	("Manhunters", None),
	("Mantis", None),
	("Marrow", None),
	("Massacre", None),
	("Master Mold", None),
	("Master Pandemonium", None),
	("Master of the World", None),
	("Mastermind", None),
	("Masters of Evil", None),
	("Matter Master", None),
	("Maxie Zeus", None),
	("Maxima", None),
	("Maximus", None),
	("Medusa", None),
	("Menace", None),
	("Mephisto", None),
	("Mercy", None),
	("Merlyn", None),
	("Metallo", None),
	("MF DOOM", None),
	("Midnight Sun", None),
	("Mimic", None),
	("Mindblast", None),
	("Miracle Man", None),
	("Mirror Master", None),
	("Misfit", None),
	("Mist", None),
	("Mister Hyde", None),
	("Mister Sinister", None),
	("Mojo Jojo", None),
	("Mole Man", None),
	("Molecule Man", None),
	("Molloch", None),
	("Moloid subterraneans", None),
	("Molten Man", None),
	("Molten Man-Thing", None),
	("Mongal", None),
	("Mongul", None),
	("Mongul II", None),
	("Monocle", None),
	("Monsieur Stigmonus", None),
	("Moondark", None),
	("Moonstone", None),
	("Morgan Edge", None),
	("Morgan le Fay", None),
	("Morlun", None),
	("Mortalla", None),
	("Mortician", None),
	("Moses Magnum", None),
	("Mothergod", None),
	("Mr. Felonious Gru", None),
	("Mr. Freeze", None),
	("Mr. Mxyzptlk", None),
	("Mr. Twister", None),
	("Mud Pack", None),
	("Murmur", None),
	("Mysteria", None),
	("Mysterio", None),
	("Mystique", None),
	("NKVDemon", None),
	("Naga", None),
	("Nebula", None),
	("Needle", None),
	("Nemesis Kid", None),
	("Nero", None),
	("Neron", None),
	("Neutron", None),
	("New Wave", None),
	("Nightmare", None),
	("Nocturna", None),
	("Northwind", None),
	("Nyssa Raatko", None),
	("O.G.R.E.", None),
	("Ocean Master", None),
	("Omega Red", None),
	("Onimar Synn", None),
	("Onomatopoeia", None),
	("Onslaught", None),
	("Orca", None),
	("Ord", None),
	("Orka", None),
	("Osira", None),
	("Overlord", None),
	("Owen Mercer", None),
	("Owlman", None),
	("Ozymandias", None),
	("Parademon", None),
	("Parademons", None),
	("Paragon", None),
	("Parallax", None),
	("Parasite", None),
	("Paste-Pot Pete", None),
	("Peek-a-Boo", None),
	("Penguin", None),
	("Penny Plunderer", None),
	("Persuader", None),
	("Phantazia", None),
	("Pharaoh Rama Tut", None),
	("Pharzoof", None),
	("Phobia", None),
	("Pied Piper", None),
	("Pink Pearl", None),
	("Plantman", None),
	("Plastique", None),
	("Poison Ivy", None),
	("Porcupine", None),
	("Portal", None),
	("Poundcakes", None),
	("Power Man", None),
	("Prank", None),
	("Prankster", None),
	("Pretty Persuasions", None),
	("Preus", None),
	("Princess Morbucks", None),
	("Princess Python", None),
	("Professor Hugo Strange", None),
	("Professor Ivo", None),
	("Professor Padraic Ratigan", None),
	("Prometheus", None),
	("Psycho-Man", None),
	("Psycho-Pirate", None),
	("Punisher", None),
	("Purgatori", None),
	("Quantum", None),
	("Queen Bee", None),
	("Queen Clea", None),
	("Queen of Fables", None),
	("Quicksand", None),
	("Quicksilver", None),
	("Qwsp", None),
	("Ra's al Ghul", None),
	("Rad", None),
	("Radioactive Man", None),
	("Rag Doll", None),
	("Rainbow Raider", None),
	("Rainbow Raiders", None),
	("Rampage", None),
	("Ratcatcher", None),
	("Reaper", None),
	("Red Ghost", None),
	("Red Hood", None),
	("Red Skull", None),
	("Resistants", None),
	("Reverse Flash", None),
	("Riddler", None),
	("Riddler's Daughter", None),
	("Ringmaster", None),
	("Ronan the Accuser", None),
	("Rose, Thorn", None),
	("Roulette", None),
	("Roxy Rocket", None),
	("Royal Flush Gang", None),
	("Rupert Thorne", None),
	("Russian", None),
	("SKULL", None),
	("Sabbac", None),
	("Sabretooth", None),
	("Salome", None),
	("Sandman", None),
	("Sat-Yr9", None),
	("Saturn Queen", None),
	("Savitar", None),
	("Scandal", None),
	("Scarecrow", None),
	("Scarlet Witch", None),
	("Scavenger", None),
	("Scorch", None),
	("Scorpia", None),
	("Scream", None),
	("Sebastian Shaw", None),
	("Sedusa", None),
	("Selene", None),
	("Sensei", None),
	("Sentinels", None),
	("Set", None),
	("Shadow Thief", None),
	("Shark", None),
	("Shimmer", None),
	("Shredder", None),
	("Shriek", None),
	("Shrike", None),
	("Signalman", None),
	("Silk Fever", None),
	("Silver Banshee", None),
	("Silver Sable", None),
	("Silver Swan", None),
	("Sin", None),
	("Sinestro", None),
	("Sinister Six", None),
	("Snapdragon", None),
	("Solaris", None),
	("Solomon Grundy", None),
	("Sonar", None),
	("Southpaw", None),
	("Space Phantom", None),
	("Speed Queen", None),
	("Spellbinder", None),
	("Spencer Smythe", None),
	("Sphinx", None),
	("Spider Girl", None),
	("Spider-Woman", None),
	("Spiral", None),
	("Sportsmaster", None),
	("Spragg", None),
	("Stained Glass Scarlet", None),
	("Star Sapphire", None),
	("Starro", None),
	("Stegron", None),
	("Stompa", None),
	("Sun Girl", None),
	("Super-Skrull", None),
	("Superia", None),
	("Superman Revenge Squad", None),
	("Supreme Intelligence", None),
	("Swordsman", None),
	("Syndrome", None),
	("T.O. Morrow", None),
	("Tala", None),
	("Talia al Ghul", None),
	("Tally Man", None),
	("Talon", None),
	("Tar Pit", None),
	("Tarantula", None),
	("Tattooed Man", None),
	("Ten-Eyed Man", None),
	("Terra", None),
	("Terra-Man", None),
	("Terraxia", None),
	("Terrible Trio", None),
	("Thanos", None),
	("The Amoeba Boys", None),
	("The Awesome Android", None),
	("The Basilisk", None),
	("The Blob", None),
	("The Borg", None),
	("The Chameleon", None),
	("The Crimson Ghost", None),
	("The Fat Man", None),
	("The Fiddler", None),
	("The Gargoyle", None),
	("The Ganggreen Gang", None),
	("The General", None),
	("The Joker", None),
	("The Kree", None),
	("The Leader", None),
	("The Lightning", None),
	("The Lizard", None),
	("The Mad Mod", None),
	("The Man-Killer", None),
	("The Mekon", None),
	("The Monk", None),
	("The Orb", None),
	("The Penguin", None),
	("The Puppet Master", None),
	("The Puzzler", None),
	("The Rhino", None),
	("The Rival", None),
	("The Rowdyruff Boys", None),
	("The Scorpion", None),
	("The Separated Man", None),
	("The Shade", None),
	("The Shocker", None),
	("The Skrulls", None),
	("The Stranger", None),
	("The Terrible Tinkerer", None),
	("The Terrible Trio", None),
	("The Top", None),
	("The Vulture", None),
	("The Wingless Wizard", None),
	("The Wink", None),
	("The Yellow Claw", None),
	("They Who Wield Power", None),
	("Thinker", None),
	("Tigress", None),
	("Tim Boo Ba", None),
	("Titan", None),
	("Titania", None),
	("Titanium Man", None),
	("Titano", None),
	("Toad", None),
	("Tony Zucco", None),
	("Toyman", None),
	("Trickster", None),
	("Trigger Twins", None),
	("Trinity", None),
	("Tsunami", None),
	("Turtle", None),
	("Tweedledum", None),
	("Two-Face", None),
	("Typhoid Mary", None),
	("Ultra-Humanite", None),
	("Ultraman", None),
	("Ultron", None),
	("Umar", None),
	("Unicron", None),
	("Unus the Untouchable", None),
	("Ursa", None),
	("Valentina", None),
	("Vandal Savage", None),
	("Vanisher", None),
	("Vapor", None),
	("Venom", None),
	("Ventriloquist", None),
	("Vermin", None),
	("Vertigo", None),
	("Victor Zsasz", None),
	("Violator", None),
	("Viper", None),
	("Virman Vundabar", None),
	("Volcana", None),
	("Vulture", None),
	("Warlord Zemu", None),
	("Warmaker", None),
	("Weather Wizard", None),
	("Whiplash", None),
	("White Rabbit", None),
	("Winter Soldier", None),
	("Xemnu", None),
	("Yancy Street Gang", None),
	("Yellowjacket", None),
	("Yuga Khan", None),
	("Zaladane", None),
	("Zaran", None),
	("Zeiss", None),
	("Zoom", None),
	("Zsasz", None),
]

encouragements = [
	"ace",
	"amazing",
	"astonishing",
	"astounding",
	"awe-inspiring",
	"awesome",
	"badass",
	"beautiful",
	"bedazzling",
	"bee's knees",
	"best",
	"breathtaking",
	"brilliant",
	"cat's meow",
	"cat's pajamas",
	"classy",
	"cool",
	"dandy",
	"dazzling",
	"delightful",
	"divine",
	"doozie",
	"epic",
	"excellent",
	"exceptional",
	"exquisite",
	"extraordinary",
	"fabulous",
	"fantastic",
	"fantabulous",
	"fine",
	"finest",
	"first-class",
	"first-rate",
	"flawless",
	"funkadelic",
	"geometric",
	"glorious",
	"gnarly",
	"good",
	"grand",
	"great",
	"groovy",
	"groundbreaking",
	"hunky-dory",
	"impeccable",
	"impressive",
	"incredible",
	"kickass",
	"kryptonian",
	"laudable",
	"legendary",
	"lovely",
	"luminous",
	"magnificent",
	"majestic",
	"marvelous",
	"mathematical",
	"mind-blowing",
	"neat",
	"outstanding",
	"peachy",
	"perfect",
	"phenomenal",
	"pioneering",
	"polished",
	"posh",
	"praiseworthy",
	"premium",
	"priceless",
	"prime",
	"primo",
	"rad",
	"remarkable",
	"riveting",
	"scrumtrulescent",
	"sensational",
	"shining",
	"slick",
	"smashing",
	"solid",
	"spectacular",
	"splendid",
	"splendiferous",
	"stellar",
	"striking",
	"stunning",
	"stupendous",
	"stylish",
	"sublime",
	"super",
	"super-duper",
	"super-excellent",
	"superb",
	"superior",
	"supreme",
	"sweet",
	"swell",
	"terrific",
	"tiptop",
	"top-notch",
	"transcendent",
	"tremendous",
	"ultimate",
	"unreal",
	"well-made",
	"wicked",
	"wonderful",
	"wondrous",
	"world-class"
]

cities = [
	'Blackrest',
	'Heartshield',
	'Springwick',
	'Coldrock',
	'Hazelmire',
	'Madlight',
	'Beachband',
	'Madgrave',
	'Rageport',
	'Wolfcross',
	'Geebury',
	'Prolwood',
	'Nerough',
	'Dreupolis',
	'Modence',
	'Khok',
	'Yrille',
	'Ugrita',
	'Ilaham',
	'Ansbury',
	'Vopnafjor',
	'Medriguen',
	'Sulitere',
	'Armeles',
	'Mopra',
	'Setrond',
	'Kryvansk',
	'Weyeowen',
	'Oltash',
	'Drutsk'
]